### ISSUE TITLE
[Diamond Search] TypeError: set expected at most 1 arguments, got 8

### ISSUE THREAD

**Issue by DavidSie** [DavidSie/MotionVectorEstimator#1]
Hej, przy uruchamianiu testów Diamond Search wywala mi się na zanim testy się zaczną. Problemem jest 

``` Python
    PATTERN = set(  [  2,  0 ],
                    [  1,  1 ],
                    [  0,  2 ],
                    [ -1,  1 ],
                    [ -2,  0 ],
                    [ -1, -1 ],
                    [  0, -2 ],
                    [  1, -1 ]  )
```

dosage komunikat: 
`line 15, in LDSPGenerator
    [  1, -1 ]  )
TypeError: set expected at most 1 arguments, got 8`

Jakiego Pythona używałeś? Ja  korzystam z 2.7.6

**Comment by yay6** [comment]
naprawione
